language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  -
    provider: releases
    api_key: $GITHUB_TOKEN
    file: dist/release.zip
    skip_cleanup: true
    on:
      branch: master
