version: 2.1
orbs:
  node: circleci/node@4.1.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'cimg/node:current'
      auth:
        username: nurikk
        password: $DOCKERHUB_PASSWORD
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist/report.html
          destination: report.html
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Publish package
                command: |
                  npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  npm publish
            - run:
               name: Trigger GH action
               command: |
                  VERSION=$(node -p "require('./package.json').version")
                  JSON_PAYLOAD='{"event_type": "update_frontend", "client_payload": { "version": "'"$VERSION"'"}}'
                  curl -XPOST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/koenkk/zigbee2mqtt/dispatches --data $JSON_PAYLOAD

workflows:
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

