version: 2.1
orbs:
  node: circleci/node@4.1.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'cimg/node:current'
      auth:
        username: nurikk
        password: $DOCKERHUB_PASSWORD
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist/report.html
          destination: report.html
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Publish package
                command: npm publish
            - run:
               name: Trigger GH action
               command: 'curl -XPOST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/koenkk/zigbee2mqtt/dispatches --data "{\"event_type\": \"update_frontend\", \"client_payload\": { \"version\": \"$(node -p "require(\"./package.json\").version")\"}}"'


