version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: 'cimg/node:current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist/report.html
          destination: report.html
      - persist_to_workspace:
        root: .
        paths:
          - '*'
  publish:
    docker:
      - image: 'cimg/node:current'
    steps:
      - attach_workspace:
          at: .
      - run:
        name: Publish to npm
        command: npm run publish
workflows:
  build_and_publish:
    jobs:
      - build:
        filters:
          tags:
            only: /^\d+\.\d+\.\d+$/
      - publish:
        requires:
          - build