name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 15
        registry-url: https://registry.npmjs.org/
    - name: Restore node_modules cache
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish to npm
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN }}
    - name: Get version version
      id: frontend-version
      run: |
        version=$(node -p "require('./package.json').version")
        echo "::set-output name=version::$version"
    - name: Trigger Zigbee2MQTT update
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      run: |
        curl -XPOST -H "Authorization: token ${{ secrets.TRIGGER_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/koenkk/zigbee2mqtt/dispatches --data '{"event_type": "update_frontend", "client_payload": { "version": "${{ steps.frontend-version.outputs.version }}"}}'
